branch-defaults:
  master:
    environment: todoapp
    group_suffix: null
global:
  application_name: cloudshootout
  default_ec2_keyname: cloudshootout
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
